### ISSUE TITLE
How should these be used in practice as an end-user?

### ISSUE THREAD

**Issue by hackel** [JetBrains/web-types#12]
I can't seem to get IDEA Ultimate (2019.2.3) to recognize web-types.  As a testcase:
I created a new Vue.js project and installed bootstrap-vue and @web-types/bootstrap-vue.  When editing a Vue template, both `b-form` and `BForm` still show "Unknown html tag" as always.  Oddly, it *will* auto-complete `Form` with no prefix as coming from bootstrap-vue, along with its props.  After doing so, jumping to the declaration goes to `node_modules/bootstrap-vue/esm/mixins/form.js`.

Do I need to somehow register bootstrap-vue (or its types) as a library in my project?

**Comment by piotrtomiak** [comment]
@hackel As an end user you do not have to do anything to use web-types from supported libraries, nor should you install `@web-types/*` packages, which are published for convenience, but are automatically downloaded by IDE. IDEA doesn't have Vue.js plugin bundled, which version of the plugin do you have installed in your IDEA?

**Comment by hackel** [comment]
Ahh okay, I misunderstood the announcement and this repo then.
My Vue.js plugin is 192.6262.27.

**Comment by piotrtomiak** [comment]
@hackel No problem. Anyway, the code completion in 2019.2.* should work for you if you use single file component files (*.vue), but if you use inline templates, or you store them in separate HTML files, than you need to try out 2019.3 EAP.

**Comment by hackel** [comment]
Thank you.  I finally figured out that the download request was being blocked by my proxy.  After allowing `raw.githubusercontent.com` and `registry.npmjs.org`, it is working fine.

**Comment by piotrtomiak** [comment]
@hackel Awesome! Thanks for sharing the solution.
