### ISSUE TITLE
可否添加对 ant-design-vue 的支持？

### ISSUE THREAD

**Issue by rxliuli** [JetBrains/web-types#13]
我目前在使用 antd 的 vue 版本 <https://vue.ant.design/>，但 IDE 中只有部分标签有提示，而其他的则没有，该功能如果是通过 NPM 库 @web-types 的方式实现的，那么可否将之开放出来便于我们追加最新的标签？

![image](https://user-images.githubusercontent.com/24560368/66892452-5529d200-f01e-11e9-88a0-f2be8d742805.png)

**Comment by piotrtomiak** [comment]
@rxliuli I've created an issue in `vue-ant-design` repository to create `web-types` for the package. Feel free to comment there.
