### ISSUE TITLE
Docs: How to add css classes to a webtype?

### ISSUE THREAD

**Issue by blowsie** [JetBrains/web-types#14]
I'm looking to create a tailwind css webtype, and wondering how I can add css classes? 
I checked the schema but it wasn't immediately obvious to me.
Thanks!

**Comment by piotrtomiak** [comment]
Hi! The CSS support is not done at all. Our main focus so far was on Vue framework elements. I would appreciate any contributions to schema to support CSS. At later stage I will add support within the IDE.

**Comment by piotrtomiak** [comment]
In 2022.2 CSS is supported with Web Types. Please refer to the schema on where to contribute it.
