### ISSUE TITLE
This function seems a bit off

### ISSUE THREAD

**Issue by rxliuli** [JetBrains/web-types#15]
I feel that this library will become meaningless after vue 3 is used on a large scale, because TypeScript will provide code hints, like many React-TS libraries do. . .

> Ref: https://vue-composition-api-rfc.netlify.com/#logic-reuse-code-organization

**Comment by piotrtomiak** [comment]
@rxliuli Thanks for pointing that out. It would be great if that's true :) However, I think that it'll still be hard to get information about slots, events or directive parameters, so good documentation of the library in form of `web-types` will probably be still have it's applicability.
