### ISSUE TITLE
Boolean type expect a value

### ISSUE THREAD

**Issue by jonhuteau** [JetBrains/web-types#16]
Hi,

I'm trying to generate a web-types.json for a custom Vue framework. I can get autocomplete from PHPStorm but boolean type expects a value. 

Did I miss something ?

```json
{
  "$schema": "https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json",
  "framework": "vue",
  "name": "npm package name",
  "version": "",
  "contributions": {
    "html": {
      "tags": [
        {
          "name": "aa-btn",
          "attributes": [
            {
              "name": "badge",
              "description": "If true, disable hover & active behaviors",
              "value": {
                "kind": "expression",
                "type": "boolean"
              }
            }
          ]
        }
      ]
    }
  }
}
```

![image](https://user-images.githubusercontent.com/58468627/88305432-cca53400-cd09-11ea-8408-c01f29b4b0ba.png)

**Comment by piotrtomiak** [comment]
@jonhuteau Thanks for asking! Sorry for late reply, but I was OOO for the last 3 weeks. Could you please let me know which version of IDE are you using? There is an old syntax with `"type"` property, which is required by some older versions of JB IDEs:
```
 {
              "name": "appear",
              "description": "Whether to apply transition on initial render.",
              "value": {
                "kind": "expression",
                "type": "boolean"
              },
              "type": "boolean"
            },
```

**Comment by jonhuteau** [comment]
No problem @piotrtomiak !

I also tried what you suggested but same result.
I'm using PhpStorm 2020.2, Build #PS-202.6397.115, built on July 29, 2020.

**Comment by piotrtomiak** [comment]
@jonhuteau Thanks! I will investigate.

**Comment by piotrtomiak** [comment]
@jonhuteau - your web-types JSON is missing `types-syntax` property, so the types are not interpreted at all. Please try:
```
{
  "$schema": "https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json",
  "framework": "vue",
  "name": "npm package name",
  "version": "",
  "contributions": {
    "html": {
      "types-syntax": "typescript",
      "tags": [
        {
          "name": "aa-btn",
          "attributes": [
            {
              "name": "badge",
              "description": "If true, disable hover & active behaviors",
              "value": {
                "kind": "expression",
                "type": "boolean"
              }
            }
          ]
        }
      ]
    }
  }
}
```
I would like to avoid having an implicit `types-syntax` for a better readability of the JSON itself.

**Comment by jonhuteau** [comment]
Thanks a lot @piotrtomiak, it works as expected with `"types-syntax": "typescript"` attribute !

I was convinced it was only required if you write your library in TS...

Again, thanks for your help !
