### ISSUE TITLE
web-types entry in package.json breaks (Vue) syntax highlighting

### ISSUE THREAD

**Issue by dancarasco** [JetBrains/web-types#18]
The "web-types" entry in package.json seems to be breaking syntax highlighting in the editor, specifically with Vue:

**Without** web-types entry in package.json:

![Screenshot from 2020-09-09 15-21-58](https://user-images.githubusercontent.com/49026110/92610991-3bd1ea00-f2b0-11ea-8dcc-e3966a3c3e51.png)

**With** web-types entry in package.json:

![Screenshot from 2020-09-09 15-23-16](https://user-images.githubusercontent.com/49026110/92611179-6e7be280-f2b0-11ea-9919-cb06ca2cc7fe.png)

I also notice that IntelliJ is stuck on "Analzying" (but it isn't doing anything)

![Screenshot from 2020-09-09 15-23-54](https://user-images.githubusercontent.com/49026110/92611266-86536680-f2b0-11ea-88b2-f5b2a0b5fee1.png)

The "File" menu seems inaccessible too, clicking it does nothing, as if IntelliJ is stuck.

Removing the "web-types" entry in package.json fixes the syntax highlighting issue, and "Analyzing" message disappears.
Happy to provide the web-types json file, and any other IntelliJ debug logs needed :)

IntelliJ debug log: https://gist.github.com/dancarasco/1bcf95efefc9ee12d6bde69b9c106e53

![Screenshot from 2020-09-09 15-33-29](https://user-images.githubusercontent.com/49026110/92612505-d7b02580-f2b1-11ea-9f2a-0fbdd753a455.png)

Distributor ID:  Ubuntu
Description: Ubuntu 20.04.1 LTS
Release:	20.04
Codename: focal

IntelliJ IDEA Ultimate:

![Screenshot from 2020-09-09 15-33-09](https://user-images.githubusercontent.com/49026110/92612439-c9620980-f2b1-11ea-9bd8-08706a62742a.png)

**Comment by piotrtomiak** [comment]
@dancarasco - thanks for reporting that! Just in time. I have fixed the issue in Vue plugin already, but failed to cherrypick it to 202 release branch. I've done that just now and the fix will be in the 2020.2.2 release next week.
