### ISSUE TITLE
web-types.json not loaded in my WebStorm 2020.2.2

### ISSUE THREAD

**Issue by joeherold** [JetBrains/web-types#19]
Hey @piotrtomiak ,

as mentioned in the vue global conf amsterdam, I can not get my web-types.json to work on my machine.
Intresting is, it worked on your machine with the exactly same web-types.json file

web-types:
https://gist.github.com/joeherold/c1fd371ad40f706790ace2fda37e11e7

![image](https://user-images.githubusercontent.com/3911545/93516521-71b74400-f92a-11ea-9648-a2329a69dc22.png)
should provide api-key as a suggesetion

Thank you a lot!
Johannes Pichler

**Comment by piotrtomiak** [comment]
@joeherold Coul you share WebStorm log (Help -> Show Log in finder) ? Can you share your library's package.json?

**Comment by joeherold** [comment]
Hey @piotrtomiak ,

sure, here you are. Log-File is huge... ~8MB

```json
{
  "name": "@xxxx/xxxx",
  "version": "0.1.7",
  "description": "Vue Component Library with types",
  "author": {
    "email": "xxx",
    "name": "Johannes Pichler",
    "url": "xxxx"
  },
  "scripts": {
    "docs:gen": "vue-docgen -c docgen.config.js && vue-docgen-web-types",
    "serve": "vue-cli-service serve",
    "build:skip": "vue-cli-service build --skip-plugins vue-i18n,i18n,vuetify,lodash --target lib --name vue-ui src/plugin.ts --dest lib --fix",
    "build": "vue-cli-service build --skip-plugins lodash --target lib --name vue-ui src/plugin.ts --dest lib --fix",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint",
    "build:local": "npm run build && npm run build:pack",
    "build:pack": "npm pack",
    "i18n:report": "vue-cli-service i18n:report --src './src/**/*.?(js|vue)' --locales './src/locales/**/*.json'"
  },
  "web-types": "web-types.json",
  "main": "lib/vue-ui.common.js",
  "types": "lib/plugin.d.ts",
  "files": [
    "lib/*",
    "src/types/*",
    "src/components/*",
    "src/lib/*",
    "src/**/*.d.ts",
    "*.json"
  ],
  "dependencies": {
    "moment": "^2.28.0"
  },
  "devDependencies": {
    "@intlify/vue-i18n-loader": "^1.0.0",
    "@types/googlemaps": "^3.39.13",
    "@types/jest": "^24.0.19",
    "@types/lodash": "^4.14.161",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-service": "^4.5.6",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "@vue/test-utils": "^1.0.3",
    "bili": "^5.0.5",
    "core-js": "^3.6.5",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "reflect-metadata": "^0.1.13",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.2",
    "typescript": "~3.9.3",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-cli-plugin-i18n": "~1.0.1",
    "vue-cli-plugin-vuetify": "~2.0.7",
    "vue-docgen-api": "^4.32.1",
    "vue-docgen-cli": "^4.32.1",
    "vue-docgen-web-types": "^0.1.6",
    "vue-i18n": "^8.17.3",
    "vue-property-decorator": "^8.5.1",
    "vue-template-compiler": "^2.6.11",
    "vuetify": "^2.2.11",
    "vuetify-loader": "^1.3.0"
  },
  "peerDependencies": {
    "lodash": "^4.17.20",
    "vue": "^2.6.11",
    "vue-i18n": "^8.17.3",
    "vuetify": "^2.2.11"
  },
  "optionalDependencies": {
    "vue": "2.x",
    "vuetify": "2.x",
    "lodash": "^4.17.20",
    "vue-i18n": "^8.17.3"
  }
}
```
My Log File is Huge....
[idea.log](https://github.com/JetBrains/web-types/files/5245066/idea.log)

**Comment by piotrtomiak** [comment]
@joeherold There is nothing in the log, unfortunately (you can delete the link). I've also used the same package.json and the same web-types files. My only guess is that's Windows problem and I'll check it out on Monday.

**Comment by joeherold** [comment]
THX - curiouse if it is a windows issue

**Comment by piotrtomiak** [comment]
@joeherold there is one more thing, which comes to my mind. Is your package included directly into the project, or indirectly? Does it have a grey folder, meaning it's indexed, or orange one, meaning it's not?

<img width="339" alt="web-types json 2020-09-21 09-49-54" src="https://user-images.githubusercontent.com/4244523/93743271-08685700-fbf0-11ea-9243-9288aeb90fce.png">

**Comment by joeherold** [comment]
I will check it today and inform you

**Comment by joeherold** [comment]
folder of the package is grey. and yes, it is added directly via **npm i** as a dependency
![image](https://user-images.githubusercontent.com/3911545/94082079-610e3e80-fe00-11ea-8c02-888c09c3fd8f.png)

**Comment by piotrtomiak** [comment]
@joeherold I was finally able to check this out on Windows and it works for me, except for navigation. The `\\` needs to be replaced with `/` for navigation to components source to work. I should fix the bug soon in the generator pacakge. Could you please replace your `vue-ui` folder with this one [vue-ui.zip](https://github.com/JetBrains/web-types/files/5291959/vue-ui.zip) and let me know if code completion works. I've used your `package.json` and your `web-types.json`, where I've just changed `source` to enable navigation.

**Comment by piotrtomiak** [comment]
@joeherold - I am closing the issue due to inactivity, if you are still experiencing the issues, please open a new one.
