### ISSUE TITLE
$schema

### ISSUE THREAD

**Issue by KaelWD** [JetBrains/web-types#2]
The example packages have `$schema` as a relative path, but I'm not sure how this translates when distributing a web-types.json with my own package. 
Should I:
 - Omit it?
 - Copy the web-types.schema.json to my own project?
 - Something else?

The schema.json has `"$schema": "http://json-schema.org/draft-07/schema#"`, is there a similar URL we can use to refer to this?

**Comment by piotrtomiak** [comment]
@KaelWD Thanks for your interest in web-types! I am glad to see them integrated into vuetify build. The schema for `web-types.json` is not yet public, as I wanted to gather more feedback before publishing it. WebStorm itself ignores the `$schema` property for now, so you can either skip it or package it with the library for completeness.

**Comment by piotrtomiak** [comment]
@KaelWD Please track issue #4 to get notified when I publish the schema.

**Comment by vaibhavhrt** [comment]
@piotrtomiak any idea how long before it gets published. If won't be too long(week or two) I will hold my PR till then, otherwise we will look into alternatives.

**Comment by piotrtomiak** [comment]
@vaibhavhrt I think it should be around a week or two; there are some changes needed for better Quasar framework support and once that is done I will publish the first version of schema. Do you miss anything in the web-types schema?

**Comment by vaibhavhrt** [comment]
No, generating a web-types.json identical (I guess, so that that can't really check line by line) to the one this repo. @KaelWD what should we do?

**Comment by piotrtomiak** [comment]
@KaelWD @vaibhavhrt I've updated the schema today to accommodate required changes for Quasar team. Please have a look at the example file I've put into examples folder. I have opened PR to publish schema on schemastore.org and I hope the schema will be available publicly soon. Let me know if you have any questions!

**Comment by vaibhavhrt** [comment]
@piotrtomiak thanks, I will take a look at it on weekend and update my PR if necessary.

**Comment by piotrtomiak** [comment]
@vaibhavhrt @KaelWD I can't get my schema published to SchemaStore, so please use:
```
https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json
```
for now. I think it's a reasonable solution till I am able to have the schema published.

**Comment by vaibhavhrt** [comment]
Totally forgot about it, @KaelWD  I will update my PR soon.

**Comment by piotrtomiak** [comment]
The shcema has been finally published on Schema store, so you can use either URL - README has been updated with correct URLs.
