### ISSUE TITLE
Using a configuration file with --config

### ISSUE THREAD

**Issue by dancarasco** [JetBrains/web-types#20]
Not a bug - just need some help! - Attempting to change/add an array of directories to the 'components' array in WebTypesBuilderConfig, what is the recommended way to pass this into the --config option? Create a new ts file, Implement WebTypesBuilderConfig and all the properties, override them in the constructor and point --config to a new .ts file? 

I tend to work mainly with .js and .json files in this project, we don't compile TS so trying to work out the best approach to this. So far I haven't been able to get the doc gen to pick up a --config file.

Thanks!

**Comment by piotrtomiak** [comment]
The config file is included with `require` so it should be either JSON or JS file. The `ts` typings are there to provide nice reference on the contents.

**Comment by dancarasco** [comment]
> The config file is included with `require` so it should be either JSON or JS file. The `ts` typings are there to provide nice reference on the contents.

Perfect, thank you!
