### ISSUE TITLE
How can I use web types for Vue.js?

### ISSUE THREAD

**Issue by xetra11** [JetBrains/web-types#26]
I just read an article about web-types and their use for Vue.js in WebStorm. However I do not quite understand how I as a developer can have this feature in my IntelliJ IDE. Do I need to download a plugin?

**Comment by piotrtomiak** [comment]
@xetra11 What would you need web-types for exactly? The feature is included with WebStorm and other JetBrains IDEs and if a particular library ships them, you will benefit from good documentation. If a library you're using do not contain web-types, consider contributing them to the library.

If you wish to use web-types for you local project all you do is to build them and link the file in your project's `package.json`. Please note that in such a case web-types will override all source based analysis.
