### ISSUE TITLE
"Unknown HTML Tag" - IntelliJ 2020.3.2

### ISSUE THREAD

**Issue by dancarasco** [JetBrains/web-types#27]
web-types version: 
`"vue-docgen-web-types": "^0.1.7",`

App:
`"vue": "^2.6.12"`

IntelliJ is giving the following warning message when trying to use web-types with **2020.3.2** (latest release as of writing):

![Screenshot from 2021-01-27 12-52-49](https://user-images.githubusercontent.com/49026110/105993853-c1f39f00-609e-11eb-9b7e-89bacdbf0615.png)

web-types.json has been generated with _no errors_:

![Screenshot from 2021-01-27 12-53-18](https://user-images.githubusercontent.com/49026110/105993890-cd46ca80-609e-11eb-9ff7-ba71b5355247.png)

When rolling back to IntelliJ **2020.3**, web-types works fine. Seems to only be an issue with the latest releases.

![Screenshot from 2021-01-27 12-53-38](https://user-images.githubusercontent.com/49026110/105993939-ddf74080-609e-11eb-8a58-f0b631157ffb.png)

Happy to provide any logs necessary.

**Comment by piotrtomiak** [comment]
Hi @dancarasco ! Sorry for the problem! Could you please tell me, where the web-types file is linked from? Is it the project `package.json` or is it a `node_modules` package? Have you tried invalidating caches (File > Invalidate Caches / Restart...) ?

**Comment by dancarasco** [comment]
Hi @piotrtomiak !

No worries - the web-types file is located in an npm module in the node_modules folder. It is a Vue app (plugin) that is hosted in GitHub's NPM registry. The web-types file is located in the root directory of this npm module (next to package.json) and the module's package.json contains the entry:

`"web-types": "./web-types.json",`

**File -> Invalidate Caches** seems to have no effect - only reverting to 2020.3.0 makes web-types work again.
Hope this helps, happy to provide logs.

**Comment by dancarasco** [comment]
Hey again @piotrtomiak 

https://github.com/JetBrains/web-types/issues/19

After reading this similar issue posted, I saw one of your replies mentioned checking if the node_modules folder was indexed or excluded (orange) - turns out mine were excluded.

After right clicking these and setting "Not Excluded" and letting IntelliJ re-index the project, **the web-types started working again!**

So it seems there is some difference with the newer IntelliJ builds where these folders are excluded by default and web-types ignores them. Hope this helps!

**Comment by piotrtomiak** [comment]
@dancarasco Your node_modules folder should have following "colors":
<img width="282" alt="logo-bw svg 2021-01-27 15-02-38" src="https://user-images.githubusercontent.com/4244523/106001863-c0cb6d80-60b0-11eb-8041-509c4f6cd256.png">
So some of the packages should be indexed and some others not - we index only direct dependencies from your `package.json` due to performance reasons. If the package with web-types have orange color, please ensure that it's in your project's `package.json` as a dependency.

**Comment by dancarasco** [comment]
@piotrtomiak Perfect - this makes sense now. The dependency is included in package.json "dependencies" section, but IntelliJ still marked it as excluded. Not sure if this is something to do with the "@company/package" namespacing convention GitHub registry uses:

![Screenshot from 2021-01-27 14-12-09](https://user-images.githubusercontent.com/49026110/106003002-acd03d80-60a9-11eb-8831-49efd95dbc6e.png)

However, I have manually marked these as "**Not Excluded"** now and IntelliJ is indexing them fine,. and web-types has started working again for 2020.3.2 :)

**Comment by piotrtomiak** [comment]
@dancarasco Thanks! It looks like an issue with WebStorm. It would be great if you can file an issue in our WebStorm issue tracker: https://youtrack.jetbrains.com/issues/WEB and provide more details about your setup. You can make the issue private.
