### ISSUE TITLE
Named component import

### ISSUE THREAD

**Issue by webistomin** [JetBrains/web-types#31]
Hi! I have a problem when I import vue component with the named export.

I'm making my component library, but let's take a look at `bootstrap-vue`, because they have the same problem.

When I use global vue components via `Vue.component(...)` or `Vue.use(...)` – everything fine. It shows me the description and all available props.
![image](https://user-images.githubusercontent.com/30475699/112196122-c3af8e00-8c1b-11eb-9546-323a7f219e85.png)

But when I import component in my `SFC` and register it locally – `web-types` doesn't work. It shows me only default Vue directives, attributes, etc.
![image](https://user-images.githubusercontent.com/30475699/112196518-2bfe6f80-8c1c-11eb-92f9-2a994ec4a053.png)

Thanks for helping.

**Comment by piotrtomiak** [comment]
@webistomin I am sorry that you're having this issue. Unfortunately I haven't implemented source -> web-types support in WebStorm. I've filed it as an issue in the product - https://youtrack.jetbrains.com/issue/WEB-50164 . I am now in a process of large improvements to web-types support and this issue will be fixed as part of it. You can expect something in May-June 2021 with the first EAPs of 2021.2.

**Comment by webistomin** [comment]
> @webistomin I am sorry that you're having this issue. Unfortunately I haven't implemented source -> web-types support in WebStorm. I've filed it as an issue in the product - https://youtrack.jetbrains.com/issue/WEB-50164 - please vote to receive updates. I am now in a process of large improvements to web-types support and this issue will be fixed as part of it. You can expect something in May-June 2021 with the first EAPs of 2021.2.

Thanks!

**Comment by mkarras** [comment]
Can't wait for it to be released! :)

**Comment by piotrtomiak** [comment]
@mkarras Working on it :)

**Comment by mkarras** [comment]
Hey @piotrtomiak, 2021.2 was released some days ago, but locally registered components with intellisense still not working for me. Should it work or was it not released?

**Comment by piotrtomiak** [comment]
@mkarras Sorry, it shouldn't work yet. Haven't manage to finish - the whole web-types support turned out to be much more complex in implementation than expected (as it happens quite often ;) ). I am working on Vue script setup support now and going to do a round of bugfixing, hopefully this issue will be included. You can watch the issue mentioned above to see when it's released.
