### ISSUE TITLE
extract.sh script doesn't work with Vue3

### ISSUE THREAD

**Issue by kallepyorala** [JetBrains/web-types#34]
extract.sh is using Vue2, any plans on Vue3 version?

**Comment by piotrtomiak** [comment]
@azurinspire The script was designed to scrape information from public Vue libraries, but unfortunately it wasn't really helpful and in each case web-types generation was introduced into the library build process. If you have library sources, it is much better to use `docgen` or a custom build. I don't have plans to support Vue 3, but any PRs are welcome, of course.
