### ISSUE TITLE
custom vue component tag attribute description in intellisense

### ISSUE THREAD

**Issue by halatas** [JetBrains/web-types#5]
I generated a web-types.json for locally developed vue components and want to include a description for tag attributes. Intellisense works for component and tags. I tried manually adding a description for tag attributes per schema, however it did not work.

* Would you please inform if attribute descriptions are picked up by intellisense?
* If yes, what is required in component to generate this metadata?

Best regards,

**Comment by piotrtomiak** [comment]
@halatas I am sorry, but we do not support showing documentation within WebStorm yet. This is one of the things I am going to work on in the upcoming weeks. Please follow https://youtrack.jetbrains.com/issue/WEB-40545 .

**Comment by piotrtomiak** [comment]
@halatas I've implemented support for documentation. It should be released this week or next week in WebStorm 2019.3 EAP
