### ISSUE TITLE
Priority issue with web-types and named import

### ISSUE THREAD

**Issue by siddharth223437** [JetBrains/web-types#53]
I have component library writtenin vue3. I have successfully integrated `web-types `but when i do a` named import `then i loose  features such as icon does not show up and props code suggestion does not show up. How can i make sure that code completion works with named import as well ?

**Comment by piotrtomiak** [comment]
@siddharth223437 Could you please provide some code samples of when the icons show up and when they don't?

**Comment by piotrtomiak** [comment]
I am closing the issue due to lack of response. In recent IDE versions the named import issue should be solved.
