### ISSUE TITLE
web-types not loading with intellij 2021.1

### ISSUE THREAD

**Issue by siddharth223437** [JetBrains/web-types#54]
In my vue 3 component library's package.json i am using  `"web-types": "./ais-components.web-types.json",`. However i am not getting any code suggestion in library consuming app.

`Package.json`

```
  "module": "./dist/ais-components.es.js",
  "main": "./dist/ais-components.umd.js",
  "web-types": "./ais-components.web-types.json",
  "exports": {
    ".": {
      "import": "./dist/ais-components.es.js",
      "require": "./dist/ais-components.umd.js"
    },
```

I also don't see any error in my intellij logs.

**Comment by piotrtomiak** [comment]
@siddharth223437 Could you please share an example library code, it's difficult to say why this doesn't work without more information.

**Comment by piotrtomiak** [comment]
@siddharth223437 Closing the issue due to lack of response. Feel free to open a new one if you still experience the problems.
