### ISSUE TITLE
Lit web-types IDE autodetection

### ISSUE THREAD

**Issue by jpradelle** [JetBrains/web-types#56]
I don't get how to have IDE auto loading `@web-types/lit` webtypes definition.

Here is a simple project:
`package.json`:
```json
{
  "name": "test",
  "version": "0.0.0",
  "dependencies": {
    "lit": "^2.0.0"
  },
  "web-types": [
    "./component-web-types.json"
  ]
}
```

Some component definition in file named `component-web-types.json`:
```json
{
    "$schema": "http://json.schemastore.org/web-types",
    "name": "test",
    "version": "0.0.0",
    "framework": "lit",
    "contributions": {
        "html": {
            "elements": [
                {
                    "name": "test-component",
                    "attributes": [
                        {
                            "name": "test-prop",
                            "required": false,
                            "value": {
                                "type": "string",
                                "required": true
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

And simple demo component `test-new.js`
```js
import {LitElement, html, css} from 'lit';
import {customElement} from 'lit/decorators.js';

@customElement('test-new')
export class TestNew extends LitElement {
  render() {
    return html`
      <test-component></test-component>
    `;
  }
}
```

I open IDE on that project, run in terminal
```
npm install
```

I open `test-new.js`, I expect to have completion on `test-component` or test-component attributes while typing it `<test-component te...></test-component>` (expecting completion when caret is at `...`), but get nothing.

When I add `@web-types/lit` as dev dependency:
```
npm i -D @web-types/lit
```
Completion works as expected.

**Comment by piotrtomiak** [comment]
@jpradelle My bad. It works like that for Vue packages, but downloads only the JSON file. I thought about implementing auto-download for others, but actually it's gonna be problematic, because of icons and possibly other files one might put into the package. Let's stay with `@web-types/lit` as a dev dependency.
