### ISSUE TITLE
How to document CSS custom properties (CSS variables) ?

### ISSUE THREAD

**Issue by jpradelle** [JetBrains/web-types#60]
I tried with a web-types file like
```json
{
    "$schema": "http://json.schemastore.org/web-types",
    "name": "test",
    "version": "0.0.0",
    "contributions": {
        "css": {
            "properties": [
                {
                    "name": "--demo-css-var",
                    "description": "Demo CSS var"
                }
            ]
        }
    }
}
```
But it seems not to be working: I don't have completion in CSS file.
Or it's working with some other conditions I don't get. I have something working in some context, but I'm not sure if this is due to web-types file.

**Comment by piotrtomiak** [comment]
@jpradelle - I've just tested it with 2022.3 and it works fine. Could you please check with latest 2022.3 RC, or share the whole project?

**Comment by piotrtomiak** [comment]
@jpradelle I am sorry - I think I've misunderstood your previous question - thanks for an example. I have not added support for CSS variables, unfortunately. I will implement them ASAP. It's not much works, but they will land only in 2023.2 (and maybe 2023.1.2)
