### ISSUE TITLE
lit support in inline html`` template literal

### ISSUE THREAD

**Issue by m4olivei** [JetBrains/web-types#64]
I'm not seeing support for [lit html](https://lit.dev/), despite appearing to have it here: https://github.com/JetBrains/web-types/tree/master/packages/lit/lit%402.0.0. I'm using PHPStorm 2022.3.1.

Specifically I'm expecting to see auto completion for event attributes (`@click` for instance) within a typical lit `render` method, but it's not working, e.g.

```typescript
import {LitElement, html} from 'lit';
import {customElement} from 'lit/decorators.js';

@customElement('my-element')
class MyComponent extends LitElement {
  // ...
  render() {
    return html`
      <button @click="${() => console.log('hello world'); }">Click me</button>
    `;
  }
}
```

Is there something I need to do to get this support for my project? I noticed that lit is missing from the [registry.json file](https://github.com/JetBrains/web-types/blob/master/packages/registry.json). Could that be the issue? Why is lit one of the only packages in this monorepo not listed there?

Thanks!

**Comment by piotrtomiak** [comment]
Hi @m4olivei! To get Lit support in your Node.js project, please install `@web-types/lit` as a dev dependency, only Vue support is automatically downloaded at this moment.

**Comment by piotrtomiak** [comment]
I have updated `packages/registry.json` and `lit` Web Types will now be automatically downloaded by the IDE.
