### ISSUE TITLE
incorrect type definition for Vue component :is

### ISSUE THREAD

**Issue by tp-nicholas** [JetBrains/web-types#67]
I [posted to StackOverflow](https://stackoverflow.com/q/75930018/356016) looking for where I could find the Vue types for `ComponentDefinition` and/or `ComponentConstructor`. There, I was told that those are pseudo-types used only in the documentation. Specifically, they appear only for the type accepted by a `component`'s `:is` prop.

PhpStorm's Web Types seem to also [believe these are actual types](https://github.com/JetBrains/web-types/blob/00dc48985094cb7821c1295e2b086b2a1a553324/packages/vue/vue%402.5.0.web-types.json#L12-L24). When I properly type my argument to `:is` as a `Component`, the IDE complains `Type Component is not assignable to type string | ComponentDefinition`.

**Comment by piotrtomiak** [comment]
@tp-nicholas - thanks for posting the issue. Please follow https://youtrack.jetbrains.com/issue/WEB-60534 for updates. This is a simple fix and it should land in 2023.1.2.
