### ISSUE TITLE
Is there an official documentation for web-types?

### ISSUE THREAD

**Issue by Autumn-one** [JetBrains/web-types#68]
I can't find the official documentation, which interferes with my learning to write web-types

**Comment by piotrtomiak** [comment]
@Autumn-one - the documentation is in progress. There is already a lot of it here: https://plugins.jetbrains.com/docs/intellij/websymbols-static-symbols.html . I still need to correct naming of the page, but hopefully it should already help a lot.

**Comment by piotrtomiak** [comment]
The documentation is now finished and README.MD now points to it.
