### ISSUE TITLE
xxx is not a valid value for v-model. Expected: v-model

### ISSUE THREAD

**Issue by anyesu** [JetBrains/web-types#79]
**First of all, I'm sorry. This bug should belong to the [intellij-community](https://github.com/JetBrains/intellij-community) project, but I don't know how to test it in that project. I see that the author of the relevant code is also you, so I came here.**

ref: https://youtrack.jetbrains.com/issue/WEB-52219

### Environment

| OS                    | IntelliJ IDEA 2023.3.2 |
| --------------------- | ---------------------- |
| Windows 10 10.0.19045 | #IU-233.13135.103      |

### Steps to reproduce

1. Create an empty project and install dependencies.

   ```shell
   npm i vue @nutui/nutui
   ```

2. Create a `Vue` file.

   ```vue
   <template>
     <nut-pull-refresh v-model="refresh" />
   </template>
   <script setup lang="ts">
   import { ref } from 'vue';

   const refresh = ref(false);
   </script>
   ```

3. Then you can see a warning appearing on the `refresh` .

   > **refresh is not a valid value for v-model. Expected: v-model**

   ![image](https://github.com/JetBrains/web-types/assets/13103906/913906f3-09bf-4685-a99b-1e7d966e7434)

### Temporary workaround

Below is the definition of `nut-pull-refresh` in the **web-types.json** file:

https://cdn.jsdelivr.net/npm/@nutui/nutui@4.3.2/dist/smartips/web-types.json

```json
{
  "name": "nut-pull-refresh",
  "slots": [],
  "events": [],
  "attributes": [
    {
      "name": "v-model",
      "default": "`false`",
      "description": "是否触发下拉刷新",
      "value": {
        "type": "boolean",
        "kind": "expression"
      }
    }
  ]
}
```

**A key point here is that the value of `type` is `boolean` .**

If you modify the `type` as follows, the warning disappears:

```diff
- "type": "boolean"
+ "type": "boolean "
```

![image](https://github.com/JetBrains/web-types/assets/13103906/b6aa7d17-c7cb-48d5-917e-1dc1d1a6fa75)

![image](https://github.com/JetBrains/web-types/assets/13103906/3290ebb8-fa4c-4a39-af65-b78743c210fa)

But this approach is obviously unrealistic, because the **web-types.json** is generated by a third-party library and is syntactically correct.

### Debugging and analysis

First, the warning is generated by the following code:

https://github.com/JetBrains/intellij-community/blob/1d4c2a0bf89a28abb2a469bdb5fee511ef05f52c/xml/xml-psi-impl/src/com/intellij/html/webSymbols/attributes/WebSymbolAttributeDescriptor.kt#L56-L60

![image](https://github.com/JetBrains/web-types/assets/13103906/32450f0b-f48d-48e7-9fb7-d1acc5e42ab4)

The `enumValues` is a non-null value and is assigned in the following code:

https://github.com/JetBrains/intellij-community/blob/1d4c2a0bf89a28abb2a469bdb5fee511ef05f52c/xml/xml-psi-impl/src/com/intellij/html/webSymbols/attributes/impl/WebSymbolHtmlAttributeInfoImpl.kt#L67-L70

![image](https://github.com/JetBrains/web-types/assets/13103906/8b65ac09-a8b2-43ad-8d87-5f5b9214a0a9)

Since the value of `attrValue?.kind` is `null` , the `kind` is assigned the default value `Kind.PLAIN` , causing `isHtmlBoolean` to become `ThreeState.YES` .

**After debugging I found the following code:**

https://github.com/JetBrains/intellij-community/blob/1d4c2a0bf89a28abb2a469bdb5fee511ef05f52c/platform/webSymbols/src/com/intellij/webSymbols/webTypes/impl/WebTypesJsonContributionAdapter.kt#L250-L260

![image](https://github.com/JetBrains/web-types/assets/13103906/c2f83ac9-2c3e-4489-b310-1d6bedc371cd)

When copying `attributeValue` to `HtmlAttributeValue()` here, the `kind` field is missing.

So I guess the problem is caused here. If you modify it like the following, it may be able to fix the problem:

```diff
 attributeValue?.let { other ->
    it.required = other.required
    it.default = other.default
    it.type = other.type
+   it.kind = other.kind
 }
```

As said before I don't know how to test it in the [intellij-community](https://github.com/JetBrains/intellij-community) , so I changed the value during the **breakpoint** to test the effect.

**The test result is that after modification, there will be no more warnings.**

> Modify the **web-types.json** file to make it reload.

![image](https://github.com/JetBrains/web-types/assets/13103906/9ee13235-d3ff-4fd1-a9b7-fdce23ac546a)

**Comment by anyesu** [comment]
@piotrtomiak Please take a look, thank you

**Comment by anyesu** [comment]
@piotrtomiak Thank you for your reply.

> in Web Types, should not be declared as `v-model`, but as `modelValue`. 

I tried this and it does fix the warning.

```diff
 {
-  "name": "v-model",
+  "name": "modelValue",
   "default": "`false`",
   "description": "是否触发下拉刷新",
   "value": {
     "type": "boolean",
     "kind": "expression"
   }
 }
```

But the hint of `v-model` will be the description in `Vue` :

![image](https://github.com/JetBrains/web-types/assets/13103906/2cd4b7e4-9a7e-4914-a580-a1267f004738)

https://github.com/JetBrains/web-types/blob/2c07137416e4151bfaf44bf3226dca7f1a5e9bd3/packages/vue/vue%403.0.0.web-types.json#L606-L614

If I apply the workaround I mentioned above, hint for `v-model` will be the description in the library, which I think should be more user friendly.

```diff
- "type": "boolean"
+ "type": "boolean "
```

![image](https://github.com/JetBrains/web-types/assets/13103906/9acec494-1a73-4436-b6ff-3052345e0467)

**Comment by anyesu** [comment]
In addition, can you help confirm whether `it.kind = other.kind` is missing? If [this](https://github.com/JetBrains/intellij-community/blob/1d4c2a0bf89a28abb2a469bdb5fee511ef05f52c/platform/webSymbols/src/com/intellij/webSymbols/webTypes/impl/WebTypesJsonContributionAdapter.kt#L253-L255) could be fixed, I think it should be a better solution.

https://github.com/JetBrains/intellij-community/blob/1d4c2a0bf89a28abb2a469bdb5fee511ef05f52c/platform/webSymbols/src/com/intellij/webSymbols/webTypes/impl/WebTypesJsonContributionAdapter.kt#L253-L255

```diff
 attributeValue?.let { other ->
    it.required = other.required
    it.default = other.default
    it.type = other.type
+   it.kind = other.kind
 }
```

**Comment by piotrtomiak** [comment]
@anyesu - I've made this on purpose, this is a conversion from an older Web Types format (1.x, which was only for Vue). In new format, you would specify a Vue component under `vue-components` instead of `elements` kind and you would specify props under `props` and some additional attributes under `attributes`.

Regarding the documentation on `v-model` - what does it say on the screenshot ? I don't know Chinese.

**Comment by anyesu** [comment]
> In new format, you would specify a Vue component under `vue-components` instead of `elements` kind and you would specify props under `props` and some additional attributes under `attributes`.

Is there a link to the relevant documentation? I don't know much about this. Or do you know of a **Vue library** that has a complete `web-types.json` example using the correct syntax?

As far as I can see, in the `web-types.json` files of some libraries, there is no `vue-components` or `elements` , and their components are under `$root/contributions/html/tags` , which is same as `vue@3.0.0.web-types.json` :

https://github.com/JetBrains/web-types/blob/2c07137416e4151bfaf44bf3226dca7f1a5e9bd3/packages/vue/vue%403.0.0.web-types.json#L1-L15

![image](https://github.com/JetBrains/web-types/assets/13103906/4e676676-4ae3-4bfc-97ef-e6c5d6205af9)

> Regarding the documentation on `v-model` - what does it say on the screenshot ? I don't know Chinese.

Sorry, this is my problem. Let me explain:

![image](https://github.com/JetBrains/web-types/assets/13103906/9acec494-1a73-4436-b6ff-3052345e0467)

In the screenshot above, the documentation `是否触发下拉刷新` is the `description` of the `modelValue` property, this can be anything. But in the `web-types.json` of third-party library, the property name is written as `v-model` .

```json
{
  "name": "nut-pull-refresh",
  "slots": [],
  "events": [],
  "attributes": [
    {
      "name": "v-model",
      "default": "`false`",
      "description": "是否触发下拉刷新", // This line will appear in the "v-model" hint
      "value": {
        "type": "boolean",
        "kind": "expression"
      }
    }
  ]
}
```

In https://github.com/youzan/vant/pull/12787 , I've fixed https://youtrack.jetbrains.com/issue/WEB-52219 using the workaround below:

- Define the `v-model` and `modelValue` properties with the same value:

  Supports both `v-model="value"` and `:model-value="value"` syntax.

  ```json
  {
    "name": "van-pull-refresh",
    "attributes": [
      {
        "name": "modelValue",
        "default": "-",
        "description": "Loading status",
        "value": {
          "type": "boolean",
          "kind": "expression"
        }
      },
      {
        "name": "v-model",
        "default": "-",
        "description": "Loading status",
        "value": {
          "type": "boolean ",
          "kind": "expression"
        }
      }
    ],
    "events": [
      {
        "name": "update:modelValue",
        "description": "Loading status\n\nEmitted when the value of `modelValue` prop changes.",
        "arguments": [
          {
            "name": "modelValue",
            "type": "boolean"
          }
        ]
      }
    ],
    "slots": []
  }
  ```

- Add `update:modelValue` event.

- Change the `type` of `v-model` to `"boolean "` instead of `"boolean"` .

  The purpose of adding the trailing space is to make the type [recognized as a `COMPLEX` type instead of a `BOOLEAN` type](https://github.com/JetBrains/intellij-community/blob/1bc5c3c9b4d731a8d1521117b3204a57e36db20e/platform/webSymbols/src/com/intellij/webSymbols/webTypes/json/WebTypesJsonUtils.kt#L377) , because `"kind": "expression"` does not take effect. This way looks a little strange, but it is indeed effective. Compared with the way changing the case (for example, changing it to `Boolean` ), it is more compatible with old IDEs ( E.g. `2021.2.3` ).

**Before**

![Before](https://github.com/youzan/vant/assets/13103906/ea6a6e3b-7241-404d-939c-c68caa7bcf1d)

**After**

![After](https://github.com/youzan/vant/assets/13103906/90614030-0d12-4b4e-bf38-0f92419ec780)

I have only verified locally that the fix works for these versions of the **IDE** ( **IntelliJ IDEA 2021.2.3** to **IntelliJ IDEA 2023.3.2** ). Due to some compatibility issues, I still need to use **IntelliJ IDEA 2021.2.3** in some projects.
