### ISSUE TITLE
Attribute enum autosuggestion

### ISSUE THREAD

**Issue by gejgalis** [JetBrains/web-types#8]
I have prepared `my-foo` tag with `size` attribute which is enumeration of values `m` and `s`. WebStorm/IntelliJ doesn't suggest those values.

Is my JSON correct or this is missing feature in WebStorm/IntelliJ ?

Having such feature would be veeeeeeery useful for cases like:
 * colour palettes
 * sizes
 * types of buttons
 * etc...

```
{
  "name": "my-foo",
  "attributes": [
    {
      "name": "size",
      "value": {
        "kind": "enum",
        "items": [
          "m",
          "s"
        ]
      },
      "default": "\"m\""
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/1484705/65247266-63083800-daf0-11e9-89c2-59b1f76e8403.png)

**Comment by piotrtomiak** [comment]
@gejgalis Your JSON is correct. The easiest way to ensure is to validate it against the schema :) Unfortunately there is still quite a few unimplemented features in the IDE. Looks like I need to create a table, which summarizes supported features of `web-types` in WebStorm (and other IDEs)

**Comment by gejgalis** [comment]
@piotrtomiak features table with planned and already implemented would be great!

**Comment by gejgalis** [comment]
Linking with YouTrack issue: https://youtrack.jetbrains.com/issue/WEB-42445

**Comment by jonhuteau** [comment]
Any news on this @piotrtomiak ?

**Comment by piotrtomiak** [comment]
@jonhuteau I plan to improve web-types support in JB IDEs within next 2-3 months, this should be one of the included improvements.

**Comment by piotrtomiak** [comment]
@itsJohnnyGrid Are you using `vue-docgen-webtypes` to generate web-types? It depends on `vue-docgen-api`, which is part of [`vue-styleguidist`](https://github.com/vue-styleguidist/vue-styleguidist) project. It looks like `vue-docgen-api` is not processing JSDoc `@type` for props, so it cannot pick up values expressed in that way. If they can process the type from JSDoc, than it could be passed to web-types and the code completion would work. E.g.:
```js
props: {
    /**
     * The size of the button.
     * @type 'sm' | 'md' | 'lg'
     */
    size: {
      type: String,
      default: "md"
    }
  },
```
should result in web-types:
```json
"attributes": [
  {
    "name": "size",
    "description": "The size of the button.",
    "value": {
      "kind": "expression",
      "type": "'sm' | 'md' | 'lg'"
    }
    "default": "\"md\""
  }
]
```
and that in turn will correctly provide possible values:
<img width="286" alt="Monosnap 2022-08-25 12-10-12" src="https://user-images.githubusercontent.com/4244523/186638085-3fa6ae69-3c07-41ce-a042-bc3cdf8fbc7e.png">
Please file an issue with the [`vue-styleguidist`](https://github.com/vue-styleguidist/vue-styleguidist) project.

**Comment by jpradelle** [comment]
To have it work I had to change `kind` by `"plain"` instead of `"expression"`:

```json
"attributes": [
  {
    "name": "size",
    "description": "The size of the button.",
    "value": {
      "kind": "plain",
      "type": "'sm' | 'md' | 'lg'"
    }
    "default": "\"md\""
  }
]
```

**Comment by piotrtomiak** [comment]
@jpradelle It depends on whether you expect a property binding, or simple text in the field. My example above was not entirely correct indeed - it is using old format for Vue files, where attributes are translated as Vue component `props`.

**Comment by MatthD** [comment]
@jpradelle When I edit my generated files it works too, but what is the syntax to have this compiled ?

```typescript
 /**
     * The size of the select.
     * @type {"md" | "lg"}
     */
    size: {
      type: String,
      default: "md",
      validator: (v: string) => ["md", "lg"].indexOf(v) !== -1,
    },
```

Compiles to: 

```json
            {
              "name": "size",
              "description": "The size of the select.",
              "value": {
                "kind": "expression",
                "type": "string"
              },
              "default": "\"md\""
            }
```

**Comment by jpradelle** [comment]
@MatthD When you say "compiled" do you mean having your code parsed and webtypes file generated by [web-component-analyzer-webtypes](https://www.npmjs.com/package/web-component-analyzer-webtypes) ? If so your syntax is good, but you have to use the latest version: `2.0.8`
